### ISSUE TITLE
Problem when the items change twice or more very quickly.

### ISSUE THREAD

**Issue by janpe** [eiriklv/react-masonry-component#86] opened 2017-06-22 15:07 UTC
If I the items change for example two times very quickly, the items sometimes fail to reorder when animations are used.

For example if I have a button that changes the props that make a rerender happen and the items transition to their new positions and I double click this button, problems occur pretty often.

If the latter click happens during the first animation then the items may get mispositioned leaving blank spaces or overlapping each other.

**Comment by afram** [comment] 2017-06-22 19:47
Hi,

Does this button toggle some state, or is it for a single state? I ask because if it's the latter then React's diffing algorithm shouldn't force a re-render on the second click because the state wouldn't have changed.

**Comment by janpe** [comment] 2017-06-22 19:56
Maybe it's easier understand if I explain the case in more detail. I have a view that has messages for one week in masonry items and I can use a control to jump between weeks and get messages for that week. So the state changes and I get a bunch of all new items. And when I do change the week when an animating of the masonry items is still ongoing then I sometimes get this problem.

**Comment by afram** [comment] 2017-06-22 20:12
aha, so it's closer to the first scenario then. :-)

Does this issue still occur when you set the transitionDuration to 0?

**Comment by janpe** [comment] 2017-06-22 20:16
No, all good with transitionDuration 0. That's also what I decided to do for now to avoid the problem.

**Comment by afram** [comment] 2017-06-22 20:18
OK that's something at least.

It may be an issue with Masonry itself instead of this component. Have you been able to reproduce this issue with vanilla Masonry at all?

**Comment by janpe** [comment] 2017-06-22 21:15
Yeah that's something I was thinking of as well. But I didn't have the time to try and reproduce this with vanilla Masonry so I decided to create an issue in this repository.

I can try this out with vanilla Masonry (and add issue to the Masonry repository if it occurs there as well) later but I'm just about to leave for a vacation for a week so I won't be able to test this before I get back in little over a week from now.

**Comment by afram** [comment] 2017-08-26 15:01
Hi @janpe 

I'm going to close this issue. Please feel free to reopen if needed :-)

**Closed by afram** 2017-08-26 15:01 UTC
